# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import bondora_api
from bondora_api.rest import ApiException
from bondora_api.apis.bid_api import BidApi


class TestBidApi(unittest.TestCase):
    """ BidApi unit test stubs """

    def setUp(self):
        self.api = bondora_api.apis.bid_api.BidApi()

    def tearDown(self):
        pass

    def test_bid_cancel_bid(self):
        """
        Test case for bid_cancel_bid

        Cancel the Bid
        """
        pass

    def test_bid_get_bid(self):
        """
        Test case for bid_get_bid

        Get the Bid
        """
        pass

    def test_bid_get_bid_summaries(self):
        """
        Test case for bid_get_bid_summaries

        Gets list of bids the investor has made.
        """
        pass

    def test_bid_make_bids(self):
        """
        Test case for bid_make_bids

        Makes bid(s) into specified auction(s).
        """
        pass


if __name__ == '__main__':
    unittest.main()
