# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

import sys

from setuptools import find_packages
from setuptools import setup

NAME = "investrhor"
VERSION = "1.0.0"

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["bondora_api", "requests-oauthlib"]

setup(
    name=NAME,
    version=VERSION,
    description="Automatic investments for Bondora",
    author_email="parruc@gmail.com",
    url="https://www.matteoparrucci.ir",
    keywords=["Investment script", "Bondora", "automatic investments"],
    install_requires=REQUIRES,
    packages=find_packages('src'),
    package_dir={'': 'src'},
    include_package_data=True,
    long_description="""Script to buy and sell bondora investments""",
    entry_points="""
    # -*- Entry points: -*-
    [console_scripts]
    bondora_secondary = investhor.scripts.invest_secondary:main
    bondora_sell = investhor.scripts.sell_stale:main
    """,
)
