# coding: utf-8

"""
    Bondora API V1

    Bondora API version 1

    OpenAPI spec version: v1
    Contact: investor@bondora.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from pprint import pformat
import re

from six import iteritems


class SecondMarketItem(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """
    def __init__(self, id=None, loan_part_id=None, amount=None, auction_id=None, auction_name=None, auction_number=None, auction_bid_number=None, country=None, credit_score=None, rating=None, interest=None, use_of_loan=None, income_verification_status=None, loan_status_code=None, loan_status_active_from=None, latest_debt_management_stage_type=None, latest_debt_management_date=None, user_name=None, gender=None, date_of_birth=None, signed_date=None, re_scheduled_on=None, debt_occured_on=None, debt_occured_on_for_secondary=None, next_payment_nr=None, next_payment_date=None, next_payment_sum=None, nr_of_scheduled_payments=None, last_payment_date=None, principal_repaid=None, interest_repaid=None, late_amount_paid=None, principal_late_amount=None, interest_late_amount=None, penalty_late_amount=None, principal_write_off_amount=None, interest_write_off_amount=None, penalty_write_off_amount=None, debt_servicing_cost_main_amount=None, debt_servicing_cost_interest_amount=None, debt_servicing_cost_penalty_amount=None, fee=None, outstanding_payments=None, desired_discount_rate=None, xirr=None, listed_on_date=None):
        """
        SecondMarketItem - a model defined in Swagger

        :param dict swaggerTypes: The key is attribute name
                                  and the value is attribute type.
        :param dict attributeMap: The key is attribute name
                                  and the value is json key in definition.
        """
        self.swagger_types = {
            'id': 'str',
            'loan_part_id': 'str',
            'amount': 'float',
            'auction_id': 'str',
            'auction_name': 'str',
            'auction_number': 'int',
            'auction_bid_number': 'int',
            'country': 'str',
            'credit_score': 'float',
            'rating': 'str',
            'interest': 'float',
            'use_of_loan': 'int',
            'income_verification_status': 'int',
            'loan_status_code': 'int',
            'loan_status_active_from': 'datetime',
            'latest_debt_management_stage_type': 'int',
            'latest_debt_management_date': 'datetime',
            'user_name': 'str',
            'gender': 'int',
            'date_of_birth': 'datetime',
            'signed_date': 'datetime',
            're_scheduled_on': 'datetime',
            'debt_occured_on': 'datetime',
            'debt_occured_on_for_secondary': 'datetime',
            'next_payment_nr': 'int',
            'next_payment_date': 'datetime',
            'next_payment_sum': 'float',
            'nr_of_scheduled_payments': 'int',
            'last_payment_date': 'datetime',
            'principal_repaid': 'float',
            'interest_repaid': 'float',
            'late_amount_paid': 'float',
            'principal_remaining': 'float',
            'principal_late_amount': 'float',
            'interest_late_amount': 'float',
            'penalty_late_amount': 'float',
            'late_amount_total': 'float',
            'principal_write_off_amount': 'float',
            'interest_write_off_amount': 'float',
            'penalty_write_off_amount': 'float',
            'debt_servicing_cost_main_amount': 'float',
            'debt_servicing_cost_interest_amount': 'float',
            'debt_servicing_cost_penalty_amount': 'float',
            'price': 'float',
            'fee': 'float',
            'total_cost': 'float',
            'outstanding_payments': 'float',
            'desired_discount_rate': 'float',
            'xirr': 'float',
            'listed_on_date': 'datetime'
        }

        self.attribute_map = {
            'id': 'Id',
            'loan_part_id': 'LoanPartId',
            'amount': 'Amount',
            'auction_id': 'AuctionId',
            'auction_name': 'AuctionName',
            'auction_number': 'AuctionNumber',
            'auction_bid_number': 'AuctionBidNumber',
            'country': 'Country',
            'credit_score': 'CreditScore',
            'rating': 'Rating',
            'interest': 'Interest',
            'use_of_loan': 'UseOfLoan',
            'income_verification_status': 'IncomeVerificationStatus',
            'loan_status_code': 'LoanStatusCode',
            'loan_status_active_from': 'LoanStatusActiveFrom',
            'latest_debt_management_stage_type': 'LatestDebtManagementStageType',
            'latest_debt_management_date': 'LatestDebtManagementDate',
            'user_name': 'UserName',
            'gender': 'Gender',
            'date_of_birth': 'DateOfBirth',
            'signed_date': 'SignedDate',
            're_scheduled_on': 'ReScheduledOn',
            'debt_occured_on': 'DebtOccuredOn',
            'debt_occured_on_for_secondary': 'DebtOccuredOnForSecondary',
            'next_payment_nr': 'NextPaymentNr',
            'next_payment_date': 'NextPaymentDate',
            'next_payment_sum': 'NextPaymentSum',
            'nr_of_scheduled_payments': 'NrOfScheduledPayments',
            'last_payment_date': 'LastPaymentDate',
            'principal_repaid': 'PrincipalRepaid',
            'interest_repaid': 'InterestRepaid',
            'late_amount_paid': 'LateAmountPaid',
            'principal_remaining': 'PrincipalRemaining',
            'principal_late_amount': 'PrincipalLateAmount',
            'interest_late_amount': 'InterestLateAmount',
            'penalty_late_amount': 'PenaltyLateAmount',
            'late_amount_total': 'LateAmountTotal',
            'principal_write_off_amount': 'PrincipalWriteOffAmount',
            'interest_write_off_amount': 'InterestWriteOffAmount',
            'penalty_write_off_amount': 'PenaltyWriteOffAmount',
            'debt_servicing_cost_main_amount': 'DebtServicingCostMainAmount',
            'debt_servicing_cost_interest_amount': 'DebtServicingCostInterestAmount',
            'debt_servicing_cost_penalty_amount': 'DebtServicingCostPenaltyAmount',
            'price': 'Price',
            'fee': 'Fee',
            'total_cost': 'TotalCost',
            'outstanding_payments': 'OutstandingPayments',
            'desired_discount_rate': 'DesiredDiscountRate',
            'xirr': 'Xirr',
            'listed_on_date': 'ListedOnDate'
        }

        self._principal_remaining = None
        self._late_amount_total = None
        self._price = None
        self._total_cost = None
        self._id = id
        self._loan_part_id = loan_part_id
        self._amount = amount
        self._auction_id = auction_id
        self._auction_name = auction_name
        self._auction_number = auction_number
        self._auction_bid_number = auction_bid_number
        self._country = country
        self._credit_score = credit_score
        self._rating = rating
        self._interest = interest
        self._use_of_loan = use_of_loan
        self._income_verification_status = income_verification_status
        self._loan_status_code = loan_status_code
        self._loan_status_active_from = loan_status_active_from
        self._latest_debt_management_stage_type = latest_debt_management_stage_type
        self._latest_debt_management_date = latest_debt_management_date
        self._user_name = user_name
        self._gender = gender
        self._date_of_birth = date_of_birth
        self._signed_date = signed_date
        self._re_scheduled_on = re_scheduled_on
        self._debt_occured_on = debt_occured_on
        self._debt_occured_on_for_secondary = debt_occured_on_for_secondary
        self._next_payment_nr = next_payment_nr
        self._next_payment_date = next_payment_date
        self._next_payment_sum = next_payment_sum
        self._nr_of_scheduled_payments = nr_of_scheduled_payments
        self._last_payment_date = last_payment_date
        self._principal_repaid = principal_repaid
        self._interest_repaid = interest_repaid
        self._late_amount_paid = late_amount_paid
        self._principal_late_amount = principal_late_amount
        self._interest_late_amount = interest_late_amount
        self._penalty_late_amount = penalty_late_amount
        self._principal_write_off_amount = principal_write_off_amount
        self._interest_write_off_amount = interest_write_off_amount
        self._penalty_write_off_amount = penalty_write_off_amount
        self._debt_servicing_cost_main_amount = debt_servicing_cost_main_amount
        self._debt_servicing_cost_interest_amount = debt_servicing_cost_interest_amount
        self._debt_servicing_cost_penalty_amount = debt_servicing_cost_penalty_amount
        self._fee = fee
        self._outstanding_payments = outstanding_payments
        self._desired_discount_rate = desired_discount_rate
        self._xirr = xirr
        self._listed_on_date = listed_on_date

    @property
    def id(self):
        """
        Gets the id of this SecondMarketItem.
        Item unique identifier

        :return: The id of this SecondMarketItem.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """
        Sets the id of this SecondMarketItem.
        Item unique identifier

        :param id: The id of this SecondMarketItem.
        :type: str
        """

        self._id = id

    @property
    def loan_part_id(self):
        """
        Gets the loan_part_id of this SecondMarketItem.
        LoanPart unique identifier

        :return: The loan_part_id of this SecondMarketItem.
        :rtype: str
        """
        return self._loan_part_id

    @loan_part_id.setter
    def loan_part_id(self, loan_part_id):
        """
        Sets the loan_part_id of this SecondMarketItem.
        LoanPart unique identifier

        :param loan_part_id: The loan_part_id of this SecondMarketItem.
        :type: str
        """

        self._loan_part_id = loan_part_id

    @property
    def amount(self):
        """
        Gets the amount of this SecondMarketItem.
        Investment amount

        :return: The amount of this SecondMarketItem.
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """
        Sets the amount of this SecondMarketItem.
        Investment amount

        :param amount: The amount of this SecondMarketItem.
        :type: float
        """

        self._amount = amount

    @property
    def auction_id(self):
        """
        Gets the auction_id of this SecondMarketItem.
        Auction unique identifier

        :return: The auction_id of this SecondMarketItem.
        :rtype: str
        """
        return self._auction_id

    @auction_id.setter
    def auction_id(self, auction_id):
        """
        Sets the auction_id of this SecondMarketItem.
        Auction unique identifier

        :param auction_id: The auction_id of this SecondMarketItem.
        :type: str
        """

        self._auction_id = auction_id

    @property
    def auction_name(self):
        """
        Gets the auction_name of this SecondMarketItem.
        Auction name

        :return: The auction_name of this SecondMarketItem.
        :rtype: str
        """
        return self._auction_name

    @auction_name.setter
    def auction_name(self, auction_name):
        """
        Sets the auction_name of this SecondMarketItem.
        Auction name

        :param auction_name: The auction_name of this SecondMarketItem.
        :type: str
        """

        self._auction_name = auction_name

    @property
    def auction_number(self):
        """
        Gets the auction_number of this SecondMarketItem.
        Auction number

        :return: The auction_number of this SecondMarketItem.
        :rtype: int
        """
        return self._auction_number

    @auction_number.setter
    def auction_number(self, auction_number):
        """
        Sets the auction_number of this SecondMarketItem.
        Auction number

        :param auction_number: The auction_number of this SecondMarketItem.
        :type: int
        """

        self._auction_number = auction_number

    @property
    def auction_bid_number(self):
        """
        Gets the auction_bid_number of this SecondMarketItem.
        Auction bid number

        :return: The auction_bid_number of this SecondMarketItem.
        :rtype: int
        """
        return self._auction_bid_number

    @auction_bid_number.setter
    def auction_bid_number(self, auction_bid_number):
        """
        Sets the auction_bid_number of this SecondMarketItem.
        Auction bid number

        :param auction_bid_number: The auction_bid_number of this SecondMarketItem.
        :type: int
        """

        self._auction_bid_number = auction_bid_number

    @property
    def country(self):
        """
        Gets the country of this SecondMarketItem.
        Residency of the borrower

        :return: The country of this SecondMarketItem.
        :rtype: str
        """
        return self._country

    @country.setter
    def country(self, country):
        """
        Sets the country of this SecondMarketItem.
        Residency of the borrower

        :param country: The country of this SecondMarketItem.
        :type: str
        """

        self._country = country

    @property
    def credit_score(self):
        """
        Gets the credit_score of this SecondMarketItem.
        <para>    1000 No previous payments problems</para>  <para>    900 Payments problems finished 24-36 months ago</para>  <para>    800 Payments problems finished 12-24 months ago</para>  <para>    700 Payments problems finished 6-12 months ago</para>  <para>    600 Payment problems finished &lt;6 months ago</para>  <para>    500 Active payment problems</para>

        :return: The credit_score of this SecondMarketItem.
        :rtype: float
        """
        return self._credit_score

    @credit_score.setter
    def credit_score(self, credit_score):
        """
        Sets the credit_score of this SecondMarketItem.
        <para>    1000 No previous payments problems</para>  <para>    900 Payments problems finished 24-36 months ago</para>  <para>    800 Payments problems finished 12-24 months ago</para>  <para>    700 Payments problems finished 6-12 months ago</para>  <para>    600 Payment problems finished &lt;6 months ago</para>  <para>    500 Active payment problems</para>

        :param credit_score: The credit_score of this SecondMarketItem.
        :type: float
        """

        self._credit_score = credit_score

    @property
    def rating(self):
        """
        Gets the rating of this SecondMarketItem.
        Bondora Rating issued by the Rating model

        :return: The rating of this SecondMarketItem.
        :rtype: str
        """
        return self._rating

    @rating.setter
    def rating(self, rating):
        """
        Sets the rating of this SecondMarketItem.
        Bondora Rating issued by the Rating model

        :param rating: The rating of this SecondMarketItem.
        :type: str
        """

        self._rating = rating

    @property
    def interest(self):
        """
        Gets the interest of this SecondMarketItem.
        Interest rate

        :return: The interest of this SecondMarketItem.
        :rtype: float
        """
        return self._interest

    @interest.setter
    def interest(self, interest):
        """
        Sets the interest of this SecondMarketItem.
        Interest rate

        :param interest: The interest of this SecondMarketItem.
        :type: float
        """

        self._interest = interest

    @property
    def use_of_loan(self):
        """
        Gets the use_of_loan of this SecondMarketItem.
        Use of loan

        :return: The use_of_loan of this SecondMarketItem.
        :rtype: int
        """
        return self._use_of_loan

    @use_of_loan.setter
    def use_of_loan(self, use_of_loan):
        """
        Sets the use_of_loan of this SecondMarketItem.
        Use of loan

        :param use_of_loan: The use_of_loan of this SecondMarketItem.
        :type: int
        """
        allowed_values = [0, 1, 2, 3, 4, 5, 6, 7, 8, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, -1]
        if use_of_loan not in allowed_values:
            raise ValueError(
                "Invalid value for `use_of_loan` ({0}), must be one of {1}"
                .format(use_of_loan, allowed_values)
            )

        self._use_of_loan = use_of_loan

    @property
    def income_verification_status(self):
        """
        Gets the income_verification_status of this SecondMarketItem.
        Income verification type

        :return: The income_verification_status of this SecondMarketItem.
        :rtype: int
        """
        return self._income_verification_status

    @income_verification_status.setter
    def income_verification_status(self, income_verification_status):
        """
        Sets the income_verification_status of this SecondMarketItem.
        Income verification type

        :param income_verification_status: The income_verification_status of this SecondMarketItem.
        :type: int
        """
        allowed_values = [1, 2, 3, 4]
        if income_verification_status not in allowed_values:
            raise ValueError(
                "Invalid value for `income_verification_status` ({0}), must be one of {1}"
                .format(income_verification_status, allowed_values)
            )

        self._income_verification_status = income_verification_status

    @property
    def loan_status_code(self):
        """
        Gets the loan_status_code of this SecondMarketItem.
        Loan status code              <para>2 Current</para><para>100 Overdue</para><para>5 60+ days overdue</para><para>4 Repaid</para><para>8 Released</para>

        :return: The loan_status_code of this SecondMarketItem.
        :rtype: int
        """
        return self._loan_status_code

    @loan_status_code.setter
    def loan_status_code(self, loan_status_code):
        """
        Sets the loan_status_code of this SecondMarketItem.
        Loan status code              <para>2 Current</para><para>100 Overdue</para><para>5 60+ days overdue</para><para>4 Repaid</para><para>8 Released</para>

        :param loan_status_code: The loan_status_code of this SecondMarketItem.
        :type: int
        """

        self._loan_status_code = loan_status_code

    @property
    def loan_status_active_from(self):
        """
        Gets the loan_status_active_from of this SecondMarketItem.
        Loan status active from

        :return: The loan_status_active_from of this SecondMarketItem.
        :rtype: datetime
        """
        return self._loan_status_active_from

    @loan_status_active_from.setter
    def loan_status_active_from(self, loan_status_active_from):
        """
        Sets the loan_status_active_from of this SecondMarketItem.
        Loan status active from

        :param loan_status_active_from: The loan_status_active_from of this SecondMarketItem.
        :type: datetime
        """

        self._loan_status_active_from = loan_status_active_from

    @property
    def latest_debt_management_stage_type(self):
        """
        Gets the latest_debt_management_stage_type of this SecondMarketItem.
        Latest debt management stage type

        :return: The latest_debt_management_stage_type of this SecondMarketItem.
        :rtype: int
        """
        return self._latest_debt_management_stage_type

    @latest_debt_management_stage_type.setter
    def latest_debt_management_stage_type(self, latest_debt_management_stage_type):
        """
        Sets the latest_debt_management_stage_type of this SecondMarketItem.
        Latest debt management stage type

        :param latest_debt_management_stage_type: The latest_debt_management_stage_type of this SecondMarketItem.
        :type: int
        """
        allowed_values = [1, 2, 3, -1]
        if not latest_debt_management_stage_type:
            latest_debt_management_stage_type = -1
        if latest_debt_management_stage_type not in allowed_values:
            raise ValueError(
                "Invalid value for `latest_debt_management_stage_type` ({0}), must be one of {1}"
                .format(latest_debt_management_stage_type, allowed_values)
            )

        self._latest_debt_management_stage_type = latest_debt_management_stage_type

    @property
    def latest_debt_management_date(self):
        """
        Gets the latest_debt_management_date of this SecondMarketItem.
        Latest debt management date

        :return: The latest_debt_management_date of this SecondMarketItem.
        :rtype: datetime
        """
        return self._latest_debt_management_date

    @latest_debt_management_date.setter
    def latest_debt_management_date(self, latest_debt_management_date):
        """
        Sets the latest_debt_management_date of this SecondMarketItem.
        Latest debt management date

        :param latest_debt_management_date: The latest_debt_management_date of this SecondMarketItem.
        :type: datetime
        """

        self._latest_debt_management_date = latest_debt_management_date

    @property
    def user_name(self):
        """
        Gets the user_name of this SecondMarketItem.
        Borrower's username

        :return: The user_name of this SecondMarketItem.
        :rtype: str
        """
        return self._user_name

    @user_name.setter
    def user_name(self, user_name):
        """
        Sets the user_name of this SecondMarketItem.
        Borrower's username

        :param user_name: The user_name of this SecondMarketItem.
        :type: str
        """

        self._user_name = user_name

    @property
    def gender(self):
        """
        Gets the gender of this SecondMarketItem.
        Borrower's Gender

        :return: The gender of this SecondMarketItem.
        :rtype: int
        """
        return self._gender

    @gender.setter
    def gender(self, gender):
        """
        Sets the gender of this SecondMarketItem.
        Borrower's Gender

        :param gender: The gender of this SecondMarketItem.
        :type: int
        """
        allowed_values = [0, 1, 2]
        if gender not in allowed_values:
            raise ValueError(
                "Invalid value for `gender` ({0}), must be one of {1}"
                .format(gender, allowed_values)
            )

        self._gender = gender

    @property
    def date_of_birth(self):
        """
        Gets the date_of_birth of this SecondMarketItem.
        Borrower's date of birth

        :return: The date_of_birth of this SecondMarketItem.
        :rtype: datetime
        """
        return self._date_of_birth

    @date_of_birth.setter
    def date_of_birth(self, date_of_birth):
        """
        Sets the date_of_birth of this SecondMarketItem.
        Borrower's date of birth

        :param date_of_birth: The date_of_birth of this SecondMarketItem.
        :type: datetime
        """

        self._date_of_birth = date_of_birth

    @property
    def signed_date(self):
        """
        Gets the signed_date of this SecondMarketItem.
        Loan issued date

        :return: The signed_date of this SecondMarketItem.
        :rtype: datetime
        """
        return self._signed_date

    @signed_date.setter
    def signed_date(self, signed_date):
        """
        Sets the signed_date of this SecondMarketItem.
        Loan issued date

        :param signed_date: The signed_date of this SecondMarketItem.
        :type: datetime
        """

        self._signed_date = signed_date

    @property
    def re_scheduled_on(self):
        """
        Gets the re_scheduled_on of this SecondMarketItem.
        Last rescheduling date

        :return: The re_scheduled_on of this SecondMarketItem.
        :rtype: datetime
        """
        return self._re_scheduled_on

    @re_scheduled_on.setter
    def re_scheduled_on(self, re_scheduled_on):
        """
        Sets the re_scheduled_on of this SecondMarketItem.
        Last rescheduling date

        :param re_scheduled_on: The re_scheduled_on of this SecondMarketItem.
        :type: datetime
        """

        self._re_scheduled_on = re_scheduled_on

    @property
    def debt_occured_on(self):
        """
        Gets the debt_occured_on of this SecondMarketItem.
        Debt occured on date

        :return: The debt_occured_on of this SecondMarketItem.
        :rtype: datetime
        """
        return self._debt_occured_on

    @debt_occured_on.setter
    def debt_occured_on(self, debt_occured_on):
        """
        Sets the debt_occured_on of this SecondMarketItem.
        Debt occured on date

        :param debt_occured_on: The debt_occured_on of this SecondMarketItem.
        :type: datetime
        """

        self._debt_occured_on = debt_occured_on

    @property
    def debt_occured_on_for_secondary(self):
        """
        Gets the debt_occured_on_for_secondary of this SecondMarketItem.
        Debt occured on date

        :return: The debt_occured_on_for_secondary of this SecondMarketItem.
        :rtype: datetime
        """
        return self._debt_occured_on_for_secondary

    @debt_occured_on_for_secondary.setter
    def debt_occured_on_for_secondary(self, debt_occured_on_for_secondary):
        """
        Sets the debt_occured_on_for_secondary of this SecondMarketItem.
        Debt occured on date

        :param debt_occured_on_for_secondary: The debt_occured_on_for_secondary of this SecondMarketItem.
        :type: datetime
        """

        self._debt_occured_on_for_secondary = debt_occured_on_for_secondary

    @property
    def next_payment_nr(self):
        """
        Gets the next_payment_nr of this SecondMarketItem.
        Next scheduled payment number

        :return: The next_payment_nr of this SecondMarketItem.
        :rtype: int
        """
        return self._next_payment_nr

    @next_payment_nr.setter
    def next_payment_nr(self, next_payment_nr):
        """
        Sets the next_payment_nr of this SecondMarketItem.
        Next scheduled payment number

        :param next_payment_nr: The next_payment_nr of this SecondMarketItem.
        :type: int
        """

        self._next_payment_nr = next_payment_nr

    @property
    def next_payment_date(self):
        """
        Gets the next_payment_date of this SecondMarketItem.
        Next scheduled payment date

        :return: The next_payment_date of this SecondMarketItem.
        :rtype: datetime
        """
        return self._next_payment_date

    @next_payment_date.setter
    def next_payment_date(self, next_payment_date):
        """
        Sets the next_payment_date of this SecondMarketItem.
        Next scheduled payment date

        :param next_payment_date: The next_payment_date of this SecondMarketItem.
        :type: datetime
        """

        self._next_payment_date = next_payment_date

    @property
    def next_payment_sum(self):
        """
        Gets the next_payment_sum of this SecondMarketItem.
        Next scheduled payment amount

        :return: The next_payment_sum of this SecondMarketItem.
        :rtype: float
        """
        return self._next_payment_sum

    @next_payment_sum.setter
    def next_payment_sum(self, next_payment_sum):
        """
        Sets the next_payment_sum of this SecondMarketItem.
        Next scheduled payment amount

        :param next_payment_sum: The next_payment_sum of this SecondMarketItem.
        :type: float
        """

        self._next_payment_sum = next_payment_sum

    @property
    def nr_of_scheduled_payments(self):
        """
        Gets the nr_of_scheduled_payments of this SecondMarketItem.
        Total number of scheduled payments

        :return: The nr_of_scheduled_payments of this SecondMarketItem.
        :rtype: int
        """
        return self._nr_of_scheduled_payments

    @nr_of_scheduled_payments.setter
    def nr_of_scheduled_payments(self, nr_of_scheduled_payments):
        """
        Sets the nr_of_scheduled_payments of this SecondMarketItem.
        Total number of scheduled payments

        :param nr_of_scheduled_payments: The nr_of_scheduled_payments of this SecondMarketItem.
        :type: int
        """

        self._nr_of_scheduled_payments = nr_of_scheduled_payments

    @property
    def last_payment_date(self):
        """
        Gets the last_payment_date of this SecondMarketItem.
        Last payment date

        :return: The last_payment_date of this SecondMarketItem.
        :rtype: datetime
        """
        return self._last_payment_date

    @last_payment_date.setter
    def last_payment_date(self, last_payment_date):
        """
        Sets the last_payment_date of this SecondMarketItem.
        Last payment date

        :param last_payment_date: The last_payment_date of this SecondMarketItem.
        :type: datetime
        """

        self._last_payment_date = last_payment_date

    @property
    def principal_repaid(self):
        """
        Gets the principal_repaid of this SecondMarketItem.
        Total principal repaid amount

        :return: The principal_repaid of this SecondMarketItem.
        :rtype: float
        """
        return self._principal_repaid

    @principal_repaid.setter
    def principal_repaid(self, principal_repaid):
        """
        Sets the principal_repaid of this SecondMarketItem.
        Total principal repaid amount

        :param principal_repaid: The principal_repaid of this SecondMarketItem.
        :type: float
        """

        self._principal_repaid = principal_repaid

    @property
    def interest_repaid(self):
        """
        Gets the interest_repaid of this SecondMarketItem.
        Total interest repaid amount

        :return: The interest_repaid of this SecondMarketItem.
        :rtype: float
        """
        return self._interest_repaid

    @interest_repaid.setter
    def interest_repaid(self, interest_repaid):
        """
        Sets the interest_repaid of this SecondMarketItem.
        Total interest repaid amount

        :param interest_repaid: The interest_repaid of this SecondMarketItem.
        :type: float
        """

        self._interest_repaid = interest_repaid

    @property
    def late_amount_paid(self):
        """
        Gets the late_amount_paid of this SecondMarketItem.
        Total late charges paid amount

        :return: The late_amount_paid of this SecondMarketItem.
        :rtype: float
        """
        return self._late_amount_paid

    @late_amount_paid.setter
    def late_amount_paid(self, late_amount_paid):
        """
        Sets the late_amount_paid of this SecondMarketItem.
        Total late charges paid amount

        :param late_amount_paid: The late_amount_paid of this SecondMarketItem.
        :type: float
        """

        self._late_amount_paid = late_amount_paid

    @property
    def principal_remaining(self):
        """
        Gets the principal_remaining of this SecondMarketItem.
        Remaining principal amount

        :return: The principal_remaining of this SecondMarketItem.
        :rtype: float
        """
        return self._principal_remaining

    @principal_remaining.setter
    def principal_remaining(self, principal_remaining):
        """
        Sets the principal_remaining of this SecondMarketItem.
        Total principal repaid amount

        :param principal_remaining: The principal_remaining of this SecondMarketItem.
        :type: float
        """

        self._principal_remaining = principal_remaining

    @property
    def principal_late_amount(self):
        """
        Gets the principal_late_amount of this SecondMarketItem.
        Principal debt amount

        :return: The principal_late_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._principal_late_amount

    @principal_late_amount.setter
    def principal_late_amount(self, principal_late_amount):
        """
        Sets the principal_late_amount of this SecondMarketItem.
        Principal debt amount

        :param principal_late_amount: The principal_late_amount of this SecondMarketItem.
        :type: float
        """

        self._principal_late_amount = principal_late_amount

    @property
    def interest_late_amount(self):
        """
        Gets the interest_late_amount of this SecondMarketItem.
        Interest debt amount

        :return: The interest_late_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._interest_late_amount

    @interest_late_amount.setter
    def interest_late_amount(self, interest_late_amount):
        """
        Sets the interest_late_amount of this SecondMarketItem.
        Interest debt amount

        :param interest_late_amount: The interest_late_amount of this SecondMarketItem.
        :type: float
        """

        self._interest_late_amount = interest_late_amount

    @property
    def penalty_late_amount(self):
        """
        Gets the penalty_late_amount of this SecondMarketItem.
        Late charges debt amount

        :return: The penalty_late_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._penalty_late_amount

    @penalty_late_amount.setter
    def penalty_late_amount(self, penalty_late_amount):
        """
        Sets the penalty_late_amount of this SecondMarketItem.
        Late charges debt amount

        :param penalty_late_amount: The penalty_late_amount of this SecondMarketItem.
        :type: float
        """

        self._penalty_late_amount = penalty_late_amount

    @property
    def late_amount_total(self):
        """
        Gets the late_amount_total of this SecondMarketItem.
        Late amount total

        :return: The late_amount_total of this SecondMarketItem.
        :rtype: float
        """
        return self._late_amount_total

    @late_amount_total.setter
    def late_amount_total(self, late_amount_total):
        """
        Sets the late_amount_total of this SecondMarketItem.
        Late charges debt amount

        :param late_amount_total: The penalty_late_amount of this SecondMarketItem.
        :type: float
        """

        self._late_amount_total = late_amount_total

    @property
    def principal_write_off_amount(self):
        """
        Gets the principal_write_off_amount of this SecondMarketItem.
        Total amount of principal written off

        :return: The principal_write_off_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._principal_write_off_amount

    @principal_write_off_amount.setter
    def principal_write_off_amount(self, principal_write_off_amount):
        """
        Sets the principal_write_off_amount of this SecondMarketItem.
        Total amount of principal written off

        :param principal_write_off_amount: The principal_write_off_amount of this SecondMarketItem.
        :type: float
        """

        self._principal_write_off_amount = principal_write_off_amount

    @property
    def interest_write_off_amount(self):
        """
        Gets the interest_write_off_amount of this SecondMarketItem.
        Total amount of interest written off

        :return: The interest_write_off_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._interest_write_off_amount

    @interest_write_off_amount.setter
    def interest_write_off_amount(self, interest_write_off_amount):
        """
        Sets the interest_write_off_amount of this SecondMarketItem.
        Total amount of interest written off

        :param interest_write_off_amount: The interest_write_off_amount of this SecondMarketItem.
        :type: float
        """

        self._interest_write_off_amount = interest_write_off_amount

    @property
    def penalty_write_off_amount(self):
        """
        Gets the penalty_write_off_amount of this SecondMarketItem.
        Total amount of penalty written off

        :return: The penalty_write_off_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._penalty_write_off_amount

    @penalty_write_off_amount.setter
    def penalty_write_off_amount(self, penalty_write_off_amount):
        """
        Sets the penalty_write_off_amount of this SecondMarketItem.
        Total amount of penalty written off

        :param penalty_write_off_amount: The penalty_write_off_amount of this SecondMarketItem.
        :type: float
        """

        self._penalty_write_off_amount = penalty_write_off_amount

    @property
    def debt_servicing_cost_main_amount(self):
        """
        Gets the debt_servicing_cost_main_amount of this SecondMarketItem.
        Total amount of principal debt servicing cost

        :return: The debt_servicing_cost_main_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._debt_servicing_cost_main_amount

    @debt_servicing_cost_main_amount.setter
    def debt_servicing_cost_main_amount(self, debt_servicing_cost_main_amount):
        """
        Sets the debt_servicing_cost_main_amount of this SecondMarketItem.
        Total amount of principal debt servicing cost

        :param debt_servicing_cost_main_amount: The debt_servicing_cost_main_amount of this SecondMarketItem.
        :type: float
        """

        self._debt_servicing_cost_main_amount = debt_servicing_cost_main_amount

    @property
    def debt_servicing_cost_interest_amount(self):
        """
        Gets the debt_servicing_cost_interest_amount of this SecondMarketItem.
        Total amount of interest debt servicing cost

        :return: The debt_servicing_cost_interest_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._debt_servicing_cost_interest_amount

    @debt_servicing_cost_interest_amount.setter
    def debt_servicing_cost_interest_amount(self, debt_servicing_cost_interest_amount):
        """
        Sets the debt_servicing_cost_interest_amount of this SecondMarketItem.
        Total amount of interest debt servicing cost

        :param debt_servicing_cost_interest_amount: The debt_servicing_cost_interest_amount of this SecondMarketItem.
        :type: float
        """

        self._debt_servicing_cost_interest_amount = debt_servicing_cost_interest_amount

    @property
    def debt_servicing_cost_penalty_amount(self):
        """
        Gets the debt_servicing_cost_penalty_amount of this SecondMarketItem.
        Total amount of penalty debt servicing cost

        :return: The debt_servicing_cost_penalty_amount of this SecondMarketItem.
        :rtype: float
        """
        return self._debt_servicing_cost_penalty_amount

    @debt_servicing_cost_penalty_amount.setter
    def debt_servicing_cost_penalty_amount(self, debt_servicing_cost_penalty_amount):
        """
        Sets the debt_servicing_cost_penalty_amount of this SecondMarketItem.
        Total amount of penalty debt servicing cost

        :param debt_servicing_cost_penalty_amount: The debt_servicing_cost_penalty_amount of this SecondMarketItem.
        :type: float
        """

        self._debt_servicing_cost_penalty_amount = debt_servicing_cost_penalty_amount

    @property
    def price(self):
        """
        Gets the price of this SecondMarketItem.
        Outstanding principal balance +/- discount or mark-up

        :return: The price of this SecondMarketItem.
        :rtype: float
        """
        return self._price

    @price.setter
    def price(self, price):
        """
        Sets the price of this SecondMarketItem.
        Total amount of penalty debt servicing cost

        :param price: The price of this SecondMarketItem.
        :type: float
        """

        self._price = price

    @property
    def fee(self):
        """
        Gets the fee of this SecondMarketItem.
        Secondary market purchase fee paid to Bondora

        :return: The fee of this SecondMarketItem.
        :rtype: float
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """
        Sets the fee of this SecondMarketItem.
        Secondary market purchase fee paid to Bondora

        :param fee: The fee of this SecondMarketItem.
        :type: float
        """

        self._fee = fee

    @property
    def total_cost(self):
        """
        Gets the total_cost of this SecondMarketItem.
        Total amount paid for purchase

        :return: The total_cost of this SecondMarketItem.
        :rtype: float
        """
        return self._total_cost


    @total_cost.setter
    def total_cost(self, total_cost):
        """
        Sets the total_cost of this SecondMarketItem.
        Total amount of penalty debt servicing cost

        :param total_cost: The total_cost of this SecondMarketItem.
        :type: float
        """

        self._total_cost = total_cost

    @property
    def outstanding_payments(self):
        """
        Gets the outstanding_payments of this SecondMarketItem.
        Total amount still to be repaid by the borrower. This includes the principal balance, accrued interest and late charges as well as any future scheduled interest payments

        :return: The outstanding_payments of this SecondMarketItem.
        :rtype: float
        """
        return self._outstanding_payments

    @outstanding_payments.setter
    def outstanding_payments(self, outstanding_payments):
        """
        Sets the outstanding_payments of this SecondMarketItem.
        Total amount still to be repaid by the borrower. This includes the principal balance, accrued interest and late charges as well as any future scheduled interest payments

        :param outstanding_payments: The outstanding_payments of this SecondMarketItem.
        :type: float
        """

        self._outstanding_payments = outstanding_payments

    @property
    def desired_discount_rate(self):
        """
        Gets the desired_discount_rate of this SecondMarketItem.
        Discount rate percent

        :return: The desired_discount_rate of this SecondMarketItem.
        :rtype: float
        """
        return self._desired_discount_rate

    @desired_discount_rate.setter
    def desired_discount_rate(self, desired_discount_rate):
        """
        Sets the desired_discount_rate of this SecondMarketItem.
        Discount rate percent

        :param desired_discount_rate: The desired_discount_rate of this SecondMarketItem.
        :type: float
        """

        self._desired_discount_rate = desired_discount_rate

    @property
    def xirr(self):
        """
        Gets the xirr of this SecondMarketItem.
        XIRR (extended internal rate of return) is a methodology to calculate the net return using the loan issued date and amount,               loan repayment dates and amounts and the principal balance according to the original repayment date.               All overdue principal payments are written off immediately. No provisions for future losses are made and only received (not accrued or scheduled)               interest payments are taken into account.

        :return: The xirr of this SecondMarketItem.
        :rtype: float
        """
        return self._xirr

    @xirr.setter
    def xirr(self, xirr):
        """
        Sets the xirr of this SecondMarketItem.
        XIRR (extended internal rate of return) is a methodology to calculate the net return using the loan issued date and amount,               loan repayment dates and amounts and the principal balance according to the original repayment date.               All overdue principal payments are written off immediately. No provisions for future losses are made and only received (not accrued or scheduled)               interest payments are taken into account.

        :param xirr: The xirr of this SecondMarketItem.
        :type: float
        """

        self._xirr = xirr

    @property
    def listed_on_date(self):
        """
        Gets the listed_on_date of this SecondMarketItem.
        Date when item was published

        :return: The listed_on_date of this SecondMarketItem.
        :rtype: datetime
        """
        return self._listed_on_date

    @listed_on_date.setter
    def listed_on_date(self, listed_on_date):
        """
        Sets the listed_on_date of this SecondMarketItem.
        Date when item was published

        :param listed_on_date: The listed_on_date of this SecondMarketItem.
        :type: datetime
        """

        self._listed_on_date = listed_on_date

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
